#!/bin/sh


FIFO=/tmp/cairo-main_controller.fifo
OUT=/var/log/cairo-main_controller.log


list() {
        echo "commands:"
        echo "log ... prints the complete server log"
        echo "msg ... print the servers output"
        echo "cmd ... execute a server command"
        echo "stat .. show launch status"
}

log() {
        cat $OUT
}

msg() {
        log | tail -n5
}

cmd() {
        echo "$1" > $FIFO
        msg
}

status() {
        systemctl status cairo-serverstart
}

if [ $# -gt 0 ]; then
        case $1 in
                list) list     ;;
                help) list     ;;
                log)  log      ;;
                msg)  msg      ;;
                cmd)  cmd "$2" ;;
                stat) status   ;;
        esac
else
        list
fi