#!/bin/sh


### BEGIN INIT INFO
# Provides:             cairo-serverstart
# Required-Start:       $all $ntp $network
# Required-Stop:        $all
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Bootstraps cairo server
# Description:          DESC
### END INIT INFO


INST_DIR='__INSTALL_DIR__'
BIN_DIR="$INST_DIR/bin/"
WALK_DIR="$INST_DIR/walkfiles/"
PYEXEC='main_controller.py'
INFILE='/tmp/cairo-main_controller.fifo'
OUTFILE='/var/log/cairo-main_controller.log'
ERRFILE='/var/log/cairo-main_controller.log'
LOGFILE="$ERRFILE"
DEVICE='/dev/ttyUSB0'


get_pid() {
        ps -ax | grep python | grep -v grep | grep -m1 python\ main_controller.py | grep -o '^\s*[0-9]\+' | grep -o '[0-9]\+'
}

log() {
        cat "$OUTFILE"
}

msg() {
        log | tail -n5
}

cmd() {
        echo "$1" > "$INFILE"
        msg
}

start() {
        # don't do anything if we are already running
        if [ ! -z $(get_pid) ]; then
                return
        fi

        # setup communication files
        if [ ! -e "$INFILE" ]; then
                mkfifo "$INFILE"
        fi

        if [ -e "$LOGFILE" ]; then
                if [ -e $"LOGFILE.1" ]; then
                        rm "$LOGFILE.1"
                fi
                mv "$LOGFILE" "$LOGFILE.1"
        fi
        touch "$LOGFILE"

        # wait for connection
        local online=false
        while [ $online = false ]; do
                wget -q --tries=10 --timeout=20 -O --spider http://www.google.com 2>&1 1>/dev/null
                if [ $? -eq 0 ]; then
                        online=true
                fi
        done

        # do run
        cd "$BIN_DIR"
        python3 "$PYEXEC" -p 11111 -d $DEVICE -w "$WALK_DIR" & 2>&1 1>/dev/null
}

stop() {
        if [ -z $(get_pid) ]; then
                return
        fi
}

restart() {
        start
        stop
}

status() {
        pid=$(get_pid)
        if [ -z $pid ]; then
                echo 'not running'
        else
                echo 'running with pid: '"$pid"
        fi
}

"$@"


# case "$1" in 
#         start)   start   ;;
#         stop)    stop    ;;
#         restart) restart ;;
#         status)  status  ;;
# esac
