#!/bin/sh


### BEGIN INIT INFO
# Provides:             cairo-serverstart
# Required-Start:       $all $ntp $network
# Required-Stop:        $all
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Bootstraps cairo server
# Description:          DESC
### END INIT INFO


INST_DIR='__INSTALL_DIR__'
MC_DIR="$INST_DIR/bin/"
WALK_DIR="$INST_DIR/walkfiles/"
PYEXEC='main_controller.py'
INFILE='/tmp/cairo-main_controller.fifo'
OUTFILE='/var/log/cairo-main_controller.log'
ERRFILE='/var/log/cairo-main_controller.log'
DEVICE='/dev/ttyUSB0'


get_pid() {
    ps -ax | grep python | grep -v grep | grep -m1 python\ main_controller.py | grep -o '^\s*[0-9]\+' | grep -o '[0-9]\+'
}

# only start if the process doesn't exist
if [ ! -z $(get_pid) ]; then
        (
                echo 'exit' > "$INFILE"
        )
fi